version: '3.8'

services:
    php:
        build:
            context: ./php
        volumes:
            - ./:/var/www/html  # Mounting your project directory
        environment:
            DATABASE_URL: ${DATABASE_URL}
        networks:
            - app_network


    nginx:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Mount your nginx.conf file
            - ./:/var/www/html  # Mount your Symfony project
        depends_on:
            - php
        networks:
            - app_network

volumes:
    db_data:
        driver: local

networks:
    app_network:
        driver: bridge
# docker run --name local-discount-bg -e POSTGRES_USER=root -e POSTGRES_PASSWORD=Apokalipsa2 -e POSTGRES_DB=discount-bg -p 5432:5432 -d postgres
